travis:
  secure:
    BINSTAR_TOKEN: VNIsR8BCNJssUQAJkTTX9CwzG6HkRC0L3n4DGRmY17tIVyqBFbFdMphvvNMbvNwIbB4+iBvjSInKJK1TAyR1bmvxyQS4cPp5PNQGIbCXCyY5Vx8b0W8lj0czju35l5RqEb+Yo10dEZc7o8gVtJs+WpRJxfGY9hzWBfacXKky34Yro02tp8GH2765JvD6Q51BvAzyXjapnJbABx6IPT93LfIkTeN+B9SW7LLyuq2otdxsyEH33VRm+XSlEugZBlvpi3mqIx+jNSd6LQ58fdHakOtsTtGRV9IrahLyZslNd1Cc+WKEQE6tg3TGdeUkwtykfqVkuuvSrXDiO825sEQGIqu2acTY2hd/LhquiU0j1RIqDvsITD1odwXQST9oJOUc3Je0S1eNjKw2NGHIAWpDnL+I0YI8qv97C8gXUuRBvxoEoD8+O5QtTIQrdixojw69Xfk0iywel+qZ4jOPN0a3FA5B8Ayy2iAVJJIFG9Y+tMPB1/xuLZzAB04Kbx24IWcjMqAIrs/4cOHkmzq6m8+vs3M1afFyZraV8G3uJ8vm2PyXatY2vaAJSNZsUjkJeQS6RUM3eyLZjfdJBY65Z9ihYzZEUOhq8xduq6ciV4+uCpeax5u0c0i7emdBJXkUfJTrl/JQXc6cby4kGV8YpoUkC3dOX2l49gVF5jkALr4Iv+4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
